<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Asplap3104" failures="1" tests="1" name="TalentSiteTestScripts" time="0.154" errors="0" timestamp="2024-11-15T19:03:25 IST">
  <testcase classname="TalentSiteTestScripts.TAL_725" name="TAL_T492" time="0.031">
    <failure type="java.lang.AssertionError" message="Error During Execution; Execution Failed More details java.lang.NullPointerException: Cannot invoke &amp;quot;org.apache.poi.hssf.usermodel.HSSFSheet.getPhysicalNumberOfRows()&amp;quot; because &amp;quot;sheet&amp;quot; is null">
      <![CDATA[java.lang.AssertionError: Error During Execution; Execution Failed More details java.lang.NullPointerException: Cannot invoke "org.apache.poi.hssf.usermodel.HSSFSheet.getPhysicalNumberOfRows()" because "sheet" is null
at org.testng.Assert.fail(Assert.java:111)
at ICar.support.TestDataExtractor.readData(TestDataExtractor.java:136)
at ICar.support.TestDataExtractor.initTestData(TestDataExtractor.java:198)
at TalentSiteTestScripts.TAL_725.TAL_T492(TAL_725.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- TAL_T492 -->
  <testcase classname="TalentSiteTestScripts.TAL_725" name="TAL_T568" time="0.0">
    <ignored/>
  </testcase> <!-- TAL_T568 -->
  <testcase classname="TalentSiteTestScripts.TAL_725" name="TAL_T568_1" time="0.0">
    <ignored/>
  </testcase> <!-- TAL_T568_1 -->
  <testcase classname="TalentSiteTestScripts.TAL_725" name="TAL_T492_1" time="0.0">
    <ignored/>
  </testcase> <!-- TAL_T492_1 -->
</testsuite> <!-- TalentSiteTestScripts -->
